// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_AltMenuScreen_Phantasia","status":true,"description":"Alternative Menu Screen Phantasia. An alternative menu based off of Tales of Phantasia.","parameters":{"\"Play Time\" Text":"Play Time","Sprite Size Ratio":"1","Show White Borders?":"false","Character Size":"48","Command Columns":"4","Command Rows":"2","Y Offset":"32"}}
];
